name: micropurchase
git:
    url: https://github.com/18F/micropurchase.git
    checkoutdir: micropurchase
    head: develop
docs:
  - docs/local_development.md
  - .ruby-version
steps:
  - text:
      - The current Ruby version is included in the [`.ruby-version`](../.ruby-version)
      - 2.3.3
    script:
      - wget -O ruby-install-0.6.1.tar.gz https://github.com/postmodern/ruby-install/archive/v0.6.1.tar.gz
      - tar -xzvf ruby-install-0.6.1.tar.gz
      - cd ruby-install-0.6.1/
      - sudo make install
      - cd ..
      - ruby-install ruby 2.3.3
  - text: `brew install phantomjs`
    script: sudo apt-get install -y phantomjs
  - text: $ bin/setup
    script: bin/setup
  - text: foreman start
    script: foreman start
  - text: up and running at\n[http://localhost:3000/](http://localhost:3000/)
    script: curl --fail http://localhost:3000/
  - text: bundle exec rake spec
    script: bundle exec rake spec
  - text: bundle exec rake cucumber
    script: bundle exec rake cucumber
# TODO: edit .env with GH secrets, SAML simulator, create an account, make it an administrator account
